// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.ComponentModel;
using System.Diagnostics;
using System.Text.Json.Nodes;

using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Kubernetes;
using Aspire.Hosting.Kubernetes.Resources;
using Aspire.Hosting.Pipelines;

using Microsoft.Extensions.DependencyInjection;

namespace Aspire.Hosting;

/// <summary>
/// Extension methods for adding KubeOps operator projects to a
/// <see cref="IDistributedApplicationBuilder"/>.
/// </summary>
public static class KubeOpsHostingExtensions
{
    /// <summary>
    /// Adds a KubeOps operator project to the distributed application model.
    /// </summary>
    /// <remarks>
    /// This is a KubeOps-flavoured wrapper around
    /// <see cref="ProjectResourceBuilderExtensions.AddProject{TProject}(IDistributedApplicationBuilder, string)"/>.
    /// It returns the standard <see cref="ProjectResource"/> builder, so all the usual
    /// Aspire extensions (<c>WithReference</c>, <c>WithEnvironment</c>, <c>WaitFor</c>, ...)
    /// apply unchanged. Pair it with <c>AddKubeOpsServiceDefaults()</c> from the
    /// <c>KubeOps.Aspire</c> package in the operator project to enable telemetry and
    /// service discovery.
    /// </remarks>
    /// <typeparam name="TProject">
    /// The operator project metadata type generated by the Aspire AppHost SDK
    /// (e.g. <c>Projects.MyOperator</c>).
    /// </typeparam>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name of the operator.</param>
    /// <returns>An <see cref="IResourceBuilder{ProjectResource}"/> for further configuration.</returns>
    public static IResourceBuilder<ProjectResource> AddKubeOps<TProject>(
        this IDistributedApplicationBuilder builder,
        [ResourceName] string name)
        where TProject : IProjectMetadata, new()
    {
        ArgumentNullException.ThrowIfNull(builder);

        var project = builder.AddProject<TProject>(name)
            .WithExplicitStart();
        var projectPath = new TProject().ProjectPath;
        var options = CreateDefaultManifestOptions(name);

        project.Resource.Annotations.Add(new KubeOpsPublishAnnotation(projectPath, options));
        ConfigureStandaloneKubeOpsPublishing(project, projectPath, options);

        return project;
    }

    /// <summary>
    /// Adds a KubeOps operator project to the distributed application model and configures its Kubernetes manifest output.
    /// </summary>
    /// <typeparam name="TProject">
    /// The operator project metadata type generated by the Aspire AppHost SDK
    /// (e.g. <c>Projects.MyOperator</c>).
    /// </typeparam>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name of the operator.</param>
    /// <param name="configureManifests">Configures KubeOps Kubernetes manifest generation.</param>
    /// <returns>An <see cref="IResourceBuilder{ProjectResource}"/> for further configuration.</returns>
    public static IResourceBuilder<ProjectResource> AddKubeOps<TProject>(
        this IDistributedApplicationBuilder builder,
        [ResourceName] string name,
        Action<KubeOpsKubernetesManifestOptions> configureManifests)
        where TProject : IProjectMetadata, new()
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(configureManifests);

        return builder.AddKubeOps<TProject>(name)
            .PublishAsKubernetesOperator(configureManifests);
    }

    /// <summary>
    /// Configures a KubeOps operator project as a Kubernetes operator in Aspire's publish output.
    /// </summary>
    /// <param name="builder">The operator project resource builder.</param>
    /// <param name="configure">Configures KubeOps Kubernetes manifest generation.</param>
    /// <returns>The same project builder so additional Aspire configuration can be chained.</returns>
    public static IResourceBuilder<ProjectResource> PublishAsKubernetesOperator(
        this IResourceBuilder<ProjectResource> builder,
        Action<KubeOpsKubernetesManifestOptions>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        var annotation = builder.Resource.Annotations.OfType<KubeOpsPublishAnnotation>().SingleOrDefault()
            ?? throw new InvalidOperationException(
                $"{nameof(PublishAsKubernetesOperator)} can only be used with project resources added via " +
                $"{nameof(AddKubeOps)}.");

        configure?.Invoke(annotation.Options);
        return builder;
    }

    /// <summary>
    /// Configures a KubeOps operator project as a Kubernetes operator for the selected compute environment.
    /// </summary>
    /// <param name="builder">The operator project resource builder.</param>
    /// <param name="target">The Kubernetes environment used for publish and deploy.</param>
    /// <param name="configure">Configures KubeOps Kubernetes manifest generation.</param>
    /// <returns>The same project builder after deployment target configuration is attached.</returns>
    public static IResourceBuilder<ProjectResource> PublishAsKubernetesOperator(
        this IResourceBuilder<ProjectResource> builder,
        IResourceBuilder<KubernetesEnvironmentResource> target,
        Action<KubeOpsKubernetesManifestOptions>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(target);

        var annotation = builder.Resource.Annotations.OfType<KubeOpsPublishAnnotation>().SingleOrDefault()
            ?? throw new InvalidOperationException(
                $"{nameof(PublishAsKubernetesOperator)} can only be used with project resources added via " +
                $"{nameof(AddKubeOps)}.");

        builder.WithComputeEnvironment(target);
        ConfigureKubeOpsPublishing(builder, annotation.ProjectPath, annotation.Options);
        return builder.PublishAsKubernetesOperator(configure);
    }

    /// <summary>
    /// Configures a KubeOps operator project to run locally with a Kubernetes environment target.
    /// </summary>
    /// <param name="builder">The operator project resource builder.</param>
    /// <param name="target">The Kubernetes environment used by the local operator process.</param>
    /// <param name="configure">Configures local run behavior.</param>
    /// <returns>The same project builder after local run configuration is attached.</returns>
    public static IResourceBuilder<ProjectResource> RunWithKubernetes(
        this IResourceBuilder<ProjectResource> builder,
        IResourceBuilder<KubernetesEnvironmentResource> target,
        Action<KubeOpsRunOptions>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(target);

        RemoveExplicitStart(builder.Resource);

        var publishAnnotation = builder.Resource.Annotations.OfType<KubeOpsPublishAnnotation>().SingleOrDefault()
            ?? throw new InvalidOperationException(
                $"{nameof(RunWithKubernetes)} can only be used with project resources added via " +
                $"{nameof(AddKubeOps)}.");

        var options = new KubeOpsRunOptions(target.Resource);
        configure?.Invoke(options);
        var runAnnotation = new KubeOpsRunAnnotation(options);
        builder.Resource.Annotations.Add(runAnnotation);
        ConfigureKubeOpsRun(builder, publishAnnotation, runAnnotation);
        return builder;
    }

    private static KubeOpsKubernetesManifestOptions CreateDefaultManifestOptions(string name)
        => new()
        {
            Namespace = $"{name}-system",
            OperatorName = name,
            ServiceAccountName = name,
        };

    private static void ConfigureKubeOpsPublishing(
        IResourceBuilder<ProjectResource> project,
        string projectPath,
        KubeOpsKubernetesManifestOptions options)
        => project.PublishAsKubernetesService(kubernetes =>
        {
            ConfigureOperatorPod(kubernetes, project.Resource.Name, options);

            foreach (var resource in GenerateKubeOpsResources(projectPath, kubernetes, options))
            {
                kubernetes.AdditionalResources.Add(resource);
            }
        });

    private static void ConfigureStandaloneKubeOpsPublishing(
        IResourceBuilder<ProjectResource> project,
        string projectPath,
        KubeOpsKubernetesManifestOptions options)
#pragma warning disable ASPIREPIPELINES001, ASPIREPIPELINES004
        => project.Resource.Annotations.Add(
            new PipelineStepAnnotation(context =>
            {
                var resource = context.Resource
                    ?? throw new InvalidOperationException("KubeOps publish step requires a resource context.");
                if (resource.GetComputeEnvironment() is KubernetesEnvironmentResource)
                {
                    return [];
                }

                return new[]
                {
                    new PipelineStep
                    {
                        Name = $"publish-{resource.Name}-kubeops",
                        Description = $"Generate KubeOps Kubernetes manifests for {resource.Name}.",
                        Resource = resource,
                        RequiredBySteps = [WellKnownPipelineSteps.Publish],
                        Action = async stepContext =>
                        {
                            var output = stepContext.Services
                                .GetRequiredService<IPipelineOutputService>()
                                .GetOutputDirectory(resource);

                            Directory.CreateDirectory(output);
                            RunKubeOpsGenerator(projectPath, output, options, "yaml");

                            await stepContext.ReportingStep.SucceedAsync(
                                $"Generated KubeOps Kubernetes manifests in '{output}'",
                                stepContext.CancellationToken);
                        },
                    },
                };
            }));
#pragma warning restore ASPIREPIPELINES001, ASPIREPIPELINES004

    private static void ConfigureKubeOpsRun(
        IResourceBuilder<ProjectResource> project,
        KubeOpsPublishAnnotation publish,
        KubeOpsRunAnnotation run)
    {
        project.OnBeforeResourceStarted(
            async (_, _, cancellationToken) => await PrepareRunCrdsAsync(publish, run, cancellationToken));
        project.OnResourceStopped(
            async (_, _, cancellationToken) => await CleanupRunCrdsAsync(run, cancellationToken));
    }

    private static async Task PrepareRunCrdsAsync(
        KubeOpsPublishAnnotation publish,
        KubeOpsRunAnnotation run,
        CancellationToken cancellationToken)
    {
        if (run.Options.CrdMode is KubeOpsRunCrdMode.Skip)
        {
            return;
        }

        foreach (var crd in GenerateKubeOpsJsonResources(publish.ProjectPath, publish.Options)
                     .Where(resource => IsKind(resource, "CustomResourceDefinition")))
        {
            var name = crd["metadata"]?["name"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(name))
            {
                continue;
            }

            var exists = await KubernetesResourceExistsAsync(run.Options.Target, "crd", name, cancellationToken);
            if (run.Options.CrdMode is KubeOpsRunCrdMode.RequireExisting)
            {
                if (!exists)
                {
                    throw new InvalidOperationException(
                        $"Kubernetes CRD '{name}' is required before running operator " +
                        $"'{publish.Options.OperatorName ?? "operator"}'.");
                }

                continue;
            }

            if (!exists || run.Options.CrdMode is KubeOpsRunCrdMode.Persistent)
            {
                await ApplyKubernetesJsonAsync(run.Options.Target, crd, cancellationToken);
            }

            if (!exists && run.Options.CrdMode is KubeOpsRunCrdMode.Ephemeral)
            {
                run.CreatedCrds.Add(name);
            }
        }
    }

    private static async Task CleanupRunCrdsAsync(
        KubeOpsRunAnnotation run,
        CancellationToken cancellationToken)
    {
        if (run.Options.CrdMode is not KubeOpsRunCrdMode.Ephemeral)
        {
            return;
        }

        foreach (var crd in run.CreatedCrds)
        {
            await RunKubectlAsync(
                run.Options.Target,
                ["delete", "crd", crd, "--ignore-not-found"],
                cancellationToken,
                throwOnError: false);
        }
    }

    private static async Task<bool> KubernetesResourceExistsAsync(
        KubernetesEnvironmentResource target,
        string kind,
        string name,
        CancellationToken cancellationToken)
    {
        var exitCode = await RunKubectlAsync(
            target,
            ["get", kind, name, "-o", "name"],
            cancellationToken,
            throwOnError: false);

        return exitCode == 0;
    }

    private static async Task ApplyKubernetesJsonAsync(
        KubernetesEnvironmentResource target,
        JsonObject resource,
        CancellationToken cancellationToken)
    {
        var file = Path.Combine(Path.GetTempPath(), "kubeops-aspire", $"{Guid.NewGuid():N}.json");
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        await File.WriteAllTextAsync(file, resource.ToJsonString(), cancellationToken);

        try
        {
            await RunKubectlAsync(target, ["apply", "-f", file], cancellationToken);
        }
        finally
        {
            File.Delete(file);
        }
    }

    private static async Task<int> RunKubectlAsync(
        KubernetesEnvironmentResource target,
        IReadOnlyList<string> arguments,
        CancellationToken cancellationToken,
        bool throwOnError = true)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = "kubectl",
            RedirectStandardError = true,
            RedirectStandardOutput = true,
            UseShellExecute = false,
        };

        if (!string.IsNullOrWhiteSpace(target.KubeConfigPath))
        {
            startInfo.ArgumentList.Add("--kubeconfig");
            startInfo.ArgumentList.Add(target.KubeConfigPath);
        }

        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = StartProcess(
            startInfo,
            "kubectl",
            "Install kubectl or ensure it is available on PATH before using RunWithKubernetes.");
        var stdoutTask = process.StandardOutput.ReadToEndAsync(cancellationToken);
        var stderrTask = process.StandardError.ReadToEndAsync(cancellationToken);
        await process.WaitForExitAsync(cancellationToken);

        if (throwOnError && process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"kubectl failed with exit code {process.ExitCode}.{Environment.NewLine}" +
                $"{await stdoutTask}{Environment.NewLine}{await stderrTask}");
        }

        return process.ExitCode;
    }

    private static void ConfigureOperatorPod(
        KubernetesResource kubernetes,
        string name,
        KubeOpsKubernetesManifestOptions options)
    {
        var podSpec = kubernetes.Workload?.PodTemplate?.Spec;
        if (podSpec is null)
        {
            return;
        }

        podSpec.ServiceAccountName = options.ServiceAccountName;

        var container = podSpec.Containers.FirstOrDefault(container => container.Name == name)
            ?? podSpec.Containers.FirstOrDefault();
        if (container is null || container.Env.Any(env => env.Name == "POD_NAMESPACE"))
        {
            return;
        }

        container.Env.Add(
            new EnvVarV1
            {
                Name = "POD_NAMESPACE",
                ValueFrom = new EnvVarSourceV1
                {
                    FieldRef = new ObjectFieldSelectorV1 { FieldPath = "metadata.namespace" },
                },
            });
    }

    private static void RemoveExplicitStart(ProjectResource resource)
    {
        var explicitStartAnnotations = resource.Annotations
            .OfType<ExplicitStartupAnnotation>()
            .Cast<IResourceAnnotation>()
            .ToList();

        foreach (var annotation in explicitStartAnnotations)
        {
            resource.Annotations.Remove(annotation);
        }
    }

    private static IEnumerable<BaseKubernetesResource> GenerateKubeOpsResources(
        string projectPath,
        KubernetesResource kubernetes,
        KubeOpsKubernetesManifestOptions options)
    {
        foreach (var json in GenerateKubeOpsJsonResources(projectPath, options))
        {
            if (IsKind(json, "Deployment"))
            {
                MergeKubeOpsDeployment(kubernetes, json);
                continue;
            }

            if (!TryCreateKubernetesResource(json, options, out var resource))
            {
                continue;
            }

            yield return resource;
        }

        if (options.IncludeServiceAccount)
        {
            yield return CreateServiceAccount(options);
        }
    }

    private static IEnumerable<JsonObject> GenerateKubeOpsJsonResources(
        string projectPath,
        KubeOpsKubernetesManifestOptions options)
    {
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "kubeops-aspire",
            Guid.NewGuid().ToString("N"));

        try
        {
            Directory.CreateDirectory(outputPath);
            RunKubeOpsGenerator(projectPath, outputPath, options, "json");

            foreach (var file in Directory.EnumerateFiles(outputPath, "*.json"))
            {
                var json = JsonNode.Parse(File.ReadAllText(file))?.AsObject();
                if (json is null)
                {
                    continue;
                }

                yield return json;
            }
        }
        finally
        {
            try
            {
                Directory.Delete(outputPath, true);
            }
            catch (DirectoryNotFoundException)
            {
                // The generator did not create an output directory.
            }
        }
    }

    private static void RunKubeOpsGenerator(
        string projectPath,
        string outputPath,
        KubeOpsKubernetesManifestOptions options,
        string format)
    {
        var arguments = new List<string>(options.KubeOpsCliArguments)
        {
            "generate",
            "operator",
            "--format",
            format,
            "--out",
            outputPath,
            "--clear-out",
            "--no-ansi",
            "--namespace",
            options.Namespace ?? $"{options.OperatorName}-system",
            "--docker-image",
            options.DockerImage,
            "--docker-image-tag",
            options.DockerImageTag,
        };

        if (!string.IsNullOrWhiteSpace(options.TargetFramework))
        {
            arguments.Add("--target-framework");
            arguments.Add(options.TargetFramework);
        }

        arguments.Add(options.OperatorName ?? "operator");
        arguments.Add(projectPath);

        var startInfo = new ProcessStartInfo
        {
            FileName = options.KubeOpsCliExecutable,
            WorkingDirectory = Path.GetDirectoryName(projectPath) ?? Environment.CurrentDirectory,
            RedirectStandardError = true,
            RedirectStandardOutput = true,
            UseShellExecute = false,
        };

        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = StartProcess(
            startInfo,
            options.KubeOpsCliExecutable,
            $"Install the KubeOps CLI or configure {nameof(KubeOpsKubernetesManifestOptions)}." +
            $"{nameof(KubeOpsKubernetesManifestOptions.KubeOpsCliExecutable)}.");

        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"KubeOps CLI failed with exit code {process.ExitCode}.{Environment.NewLine}" +
                $"{stdout}{Environment.NewLine}{stderr}");
        }
    }

    private static Process StartProcess(ProcessStartInfo startInfo, string executable, string failureHint)
    {
        try
        {
            return Process.Start(startInfo)
                ?? throw new InvalidOperationException($"Failed to start '{executable}'.");
        }
        catch (Win32Exception exception)
        {
            throw new InvalidOperationException(
                $"Failed to start '{executable}'. {failureHint}",
                exception);
        }
    }

    private static bool TryCreateKubernetesResource(
        JsonObject json,
        KubeOpsKubernetesManifestOptions options,
        out BaseKubernetesResource resource)
    {
        resource = null!;

        var apiVersion = json["apiVersion"]?.GetValue<string>();
        var kind = json["kind"]?.GetValue<string>();
        if (string.IsNullOrWhiteSpace(apiVersion) || string.IsNullOrWhiteSpace(kind) || ShouldSkip(kind, options))
        {
            return false;
        }

        RewriteServiceAccountSubjects(json, options);

        var generated = new KubeOpsGeneratedKubernetesResource(apiVersion, kind)
        {
            Metadata = CreateMetadata(json["metadata"] as JsonObject),
            Data = ConvertJson(json["data"]),
            StringData = ConvertJson(json["stringData"]),
            Type = ConvertJson(json["type"]),
            Spec = ConvertJson(json["spec"]),
            Rules = ConvertJson(json["rules"]),
            RoleRef = ConvertJson(json["roleRef"]),
            Subjects = ConvertJson(json["subjects"]),
            Webhooks = ConvertJson(json["webhooks"]),
            Secrets = ConvertJson(json["secrets"]),
            ImagePullSecrets = ConvertJson(json["imagePullSecrets"]),
        };

        resource = generated;
        return true;
    }

    private static bool ShouldSkip(string kind, KubeOpsKubernetesManifestOptions options)
        => kind is "Namespace" or "Kustomization"
           || (!options.IncludeCrds && kind is "CustomResourceDefinition")
           || (!options.IncludeRbac && kind is "ClusterRole" or "ClusterRoleBinding" or "Role" or "RoleBinding");

    private static bool IsKind(JsonObject json, string kind)
        => string.Equals(json["kind"]?.GetValue<string>(), kind, StringComparison.Ordinal);

    private static void MergeKubeOpsDeployment(KubernetesResource kubernetes, JsonObject deployment)
    {
        var generatedSpec = deployment["spec"] as JsonObject;
        if (generatedSpec is null)
        {
            return;
        }

        if (kubernetes.Workload is Deployment workload)
        {
            if (TryGetInt32(generatedSpec["replicas"], out var replicas))
            {
                workload.Spec.Replicas = replicas;
            }

            if (TryGetInt32(generatedSpec["revisionHistoryLimit"], out var revisionHistoryLimit))
            {
                workload.Spec.RevisionHistoryLimit = revisionHistoryLimit;
            }
        }

        var generatedPodSpec = generatedSpec["template"]?["spec"] as JsonObject;
        var podSpec = kubernetes.Workload?.PodTemplate?.Spec;
        if (generatedPodSpec is null || podSpec is null)
        {
            return;
        }

        if (TryGetInt64(generatedPodSpec["terminationGracePeriodSeconds"], out var terminationGracePeriodSeconds))
        {
            podSpec.TerminationGracePeriodSeconds = terminationGracePeriodSeconds;
        }

        var generatedContainer = (generatedPodSpec["containers"] as JsonArray)?
            .OfType<JsonObject>()
            .FirstOrDefault();
        var container = podSpec.Containers.FirstOrDefault();
        if (generatedContainer is null || container is null)
        {
            return;
        }

        MergeEnvironmentVariables(container, generatedContainer["env"] as JsonArray);
        MergeResourceRequirements(container, generatedContainer["resources"] as JsonObject);
    }

    private static void MergeEnvironmentVariables(ContainerV1 container, JsonArray? generatedEnvironment)
    {
        if (generatedEnvironment is null)
        {
            return;
        }

        foreach (var generatedVariable in generatedEnvironment.OfType<JsonObject>())
        {
            var name = generatedVariable["name"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(name) || container.Env.Any(env => env.Name == name))
            {
                continue;
            }

            var environmentVariable = new EnvVarV1 { Name = name };
            if (generatedVariable["value"]?.GetValue<string>() is { } value)
            {
                environmentVariable.Value = value;
            }
            else if (generatedVariable["valueFrom"]?["fieldRef"] is JsonObject fieldRef
                     && fieldRef["fieldPath"]?.GetValue<string>() is { } fieldPath)
            {
                environmentVariable.ValueFrom = new EnvVarSourceV1
                {
                    FieldRef = new ObjectFieldSelectorV1
                    {
                        FieldPath = fieldPath,
                    },
                };
            }

            container.Env.Add(environmentVariable);
        }
    }

    private static void MergeResourceRequirements(ContainerV1 container, JsonObject? generatedResources)
    {
        if (generatedResources is null)
        {
            return;
        }

        container.Resources ??= new ResourceRequirementsV1();
        CopyStringDictionary(
            generatedResources["limits"] as JsonObject,
            container.Resources.Limits);
        CopyStringDictionary(
            generatedResources["requests"] as JsonObject,
            container.Resources.Requests);
    }

    private static void CopyStringDictionary(JsonObject? source, IDictionary<string, string> target)
    {
        if (source is null)
        {
            return;
        }

        foreach (var item in ConvertStringDictionary(source) ?? [])
        {
            target[item.Key] = item.Value;
        }
    }

    private static bool TryGetInt32(JsonNode? node, out int value)
    {
        if (node is JsonValue jsonValue && jsonValue.TryGetValue<int>(out value))
        {
            return true;
        }

        value = default;
        return false;
    }

    private static bool TryGetInt64(JsonNode? node, out long value)
    {
        if (node is JsonValue jsonValue && jsonValue.TryGetValue<long>(out value))
        {
            return true;
        }

        value = default;
        return false;
    }

    private static void RewriteServiceAccountSubjects(JsonObject json, KubeOpsKubernetesManifestOptions options)
    {
        if (json["subjects"] is not JsonArray subjects)
        {
            return;
        }

        foreach (var subject in subjects.OfType<JsonObject>())
        {
            if (subject["kind"]?.GetValue<string>() is not "ServiceAccount")
            {
                continue;
            }

            subject["name"] = options.ServiceAccountName;
            subject["namespace"] = options.Namespace;
        }
    }

    private static BaseKubernetesResource CreateServiceAccount(KubeOpsKubernetesManifestOptions options)
    {
        var metadata = new ObjectMetaV1 { Name = options.ServiceAccountName };
        if (options.Namespace is { } namespaceName)
        {
            metadata.Namespace = namespaceName;
        }

        return new KubeOpsGeneratedKubernetesResource("v1", "ServiceAccount")
        {
            Metadata = metadata,
        };
    }

    private static ObjectMetaV1 CreateMetadata(JsonObject? metadata)
    {
        var result = new ObjectMetaV1();
        if (metadata?["name"]?.GetValue<string>() is { } name)
        {
            result.Name = name;
        }

        if (metadata?["namespace"]?.GetValue<string>() is { } namespaceName)
        {
            result.Namespace = namespaceName;
        }

        if (ConvertStringDictionary(metadata?["labels"] as JsonObject) is { } labels)
        {
            result.Labels = labels;
        }

        if (ConvertStringDictionary(metadata?["annotations"] as JsonObject) is { } annotations)
        {
            foreach (var annotation in annotations)
            {
                result.Annotations[annotation.Key] = annotation.Value;
            }
        }

        return result;
    }

    private static Dictionary<string, string>? ConvertStringDictionary(JsonObject? json)
        => json?.ToDictionary(
            property => property.Key,
            property => property.Value?.GetValue<string>() ?? string.Empty);

    private static object? ConvertJson(JsonNode? node)
        => node switch
        {
            null => null,
            JsonObject jsonObject => jsonObject.ToDictionary(
                property => property.Key,
                property => ConvertJson(property.Value)),
            JsonArray jsonArray => jsonArray.Select(ConvertJson).ToList(),
            JsonValue jsonValue when jsonValue.TryGetValue<string>(out var value) => value,
            JsonValue jsonValue when jsonValue.TryGetValue<bool>(out var value) => value,
            JsonValue jsonValue when jsonValue.TryGetValue<long>(out var value) => value,
            JsonValue jsonValue when jsonValue.TryGetValue<double>(out var value) => value,
            _ => node.ToJsonString(),
        };
}
