// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using Aspire.Hosting.ApplicationModel;

namespace Aspire.Hosting;

/// <summary>
/// Extension methods for adding KubeOps operator projects to a
/// <see cref="IDistributedApplicationBuilder"/>.
/// </summary>
public static class KubeOpsHostingExtensions
{
    /// <summary>
    /// Adds a KubeOps operator project to the distributed application model.
    /// </summary>
    /// <remarks>
    /// This is a KubeOps-flavoured wrapper around
    /// <see cref="ProjectResourceBuilderExtensions.AddProject{TProject}(IDistributedApplicationBuilder, string)"/>.
    /// It returns the standard <see cref="ProjectResource"/> builder, so all the usual
    /// Aspire extensions (<c>WithReference</c>, <c>WithEnvironment</c>, <c>WaitFor</c>, ...)
    /// apply unchanged. Pair it with <c>AddKubeOpsServiceDefaults()</c> from the
    /// <c>KubeOps.Aspire</c> package in the operator project to enable telemetry and
    /// service discovery.
    /// </remarks>
    /// <typeparam name="TProject">
    /// The operator project metadata type generated by the Aspire AppHost SDK
    /// (e.g. <c>Projects.MyOperator</c>).
    /// </typeparam>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name of the operator.</param>
    /// <returns>An <see cref="IResourceBuilder{ProjectResource}"/> for further configuration.</returns>
    public static IResourceBuilder<ProjectResource> AddKubeOps<TProject>(
        this IDistributedApplicationBuilder builder,
        [ResourceName] string name)
        where TProject : IProjectMetadata, new()
        => builder.AddProject<TProject>(name);
}
