// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

using FluentAssertions;

using KubeOps.Generator.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class ControllerRegistrationGeneratorTest
{
    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Not_Generate_Registrations_Without_Controllers()
    {
        var inputCompilation = string.Empty.CreateCompilation();

        var driver = CSharpGeneratorDriver.Create(new ControllerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        output.SyntaxTrees.Any(s => s.FilePath.Contains("ControllerRegistrations.g.cs")).Should().BeFalse();
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Generate_Into_Configured_Namespace()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation();
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                namespace My.Operator_Lib;
                public static class ControllerRegistrations
                {
                    public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                    {
                        builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(
            generators: [new ControllerRegistrationGenerator().AsSourceGenerator()],
            optionsProvider: TestHelperExtensions.CreateGeneratorNamespaceOptions("My.Operator-Lib"));
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("ControllerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Sanitize_Configured_Namespace()
    {
        // Segments starting with a digit or matching a reserved keyword are prefixed with an
        // underscore; invalid characters are replaced with underscores.
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation();

        var driver = CSharpGeneratorDriver.Create(
            generators: [new ControllerRegistrationGenerator().AsSourceGenerator()],
            optionsProvider: TestHelperExtensions.CreateGeneratorNamespaceOptions("9my.class.lib-x"));
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("ControllerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Contain("namespace _9my._class.lib_x;");
    }

    [Theory]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;
                
                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with direct entity type")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public abstract class EntityControllerBase<TEntity> : IEntityController<TEntity>
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityController : EntityControllerBase<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with inheritance and direct entity type")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }

                public partial class V1TestEntityController
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Partial controller class with direct entity type")]
    public void Should_Generate_Correct_Code(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation();
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new ControllerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("ControllerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
