// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

using FluentAssertions;

using KubeOps.Generator.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class ControllerRegistrationGeneratorTest
{
    [Theory]
    [InlineData(
        "",
        """
                    // <auto-generated>
                    // This code was generated by a tool.
                    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                    // </auto-generated>
                    #pragma warning disable CS1591
                    using KubeOps.Abstractions.Builder;

                    public static class ControllerRegistrations
                    {
                        public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                        {
                            return builder;
                        }
                    }
                    """,
        TestDisplayName = "No controllers defined")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;
                
                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with direct entity type")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public abstract class EntityControllerBase<TEntity> : IEntityController<TEntity>
                    where TEntity : IKubernetesObject<V1ObjectMeta>
                {
                }
                
                public sealed class V1TestEntityController : EntityControllerBase<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with inheritance and direct entity type")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }

                public partial class V1TestEntityController
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Partial controller class with direct entity type")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Entities;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class V1TestEntityLabelSelector : IEntityLabelSelector<V1TestEntity>
                {
                    public ValueTask<string?> GetLabelSelectorAsync(CancellationToken cancellationToken) =>
                        ValueTask.FromResult<string?>("managed=true");
                }

                [LabelSelector(typeof(V1TestEntityLabelSelector))]
                public sealed class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddControllerWithLabelSelector<global::V1TestEntityController, global::V1TestEntity, global::V1TestEntityLabelSelector>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with label selector attribute")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Entities;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class V1TestEntityFieldSelector : IEntityFieldSelector<V1TestEntity>
                {
                    public ValueTask<string?> GetFieldSelectorAsync(CancellationToken cancellationToken) =>
                        ValueTask.FromResult<string?>("metadata.name=my-resource");
                }

                [FieldSelector(typeof(V1TestEntityFieldSelector))]
                public sealed class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddControllerWithFieldSelector<global::V1TestEntityController, global::V1TestEntity, global::V1TestEntityFieldSelector>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Controller with field selector attribute")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Entities;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class ManagedSelector : IEntityLabelSelector<V1TestEntity>
                {
                    public ValueTask<string?> GetLabelSelectorAsync(CancellationToken cancellationToken) =>
                        ValueTask.FromResult<string?>("managed=true");
                }

                public sealed class ConfigSelector : IEntityLabelSelector<V1TestEntity>
                {
                    public ValueTask<string?> GetLabelSelectorAsync(CancellationToken cancellationToken) =>
                        ValueTask.FromResult<string?>("managed=true,config=true");
                }

                [LabelSelector(typeof(ManagedSelector))]
                public sealed class ManagedController : IEntityController<V1TestEntity>
                {
                }

                [LabelSelector(typeof(ConfigSelector))]
                public sealed class ConfigController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddControllerWithLabelSelector<global::ManagedController, global::V1TestEntity, global::ManagedSelector>();
                             builder.AddControllerWithLabelSelector<global::ConfigController, global::V1TestEntity, global::ConfigSelector>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Multiple controllers for the same entity with different label selectors")]
    public void Should_Generate_Correct_Code(string input, string expectedResult)
    {
        var inputCompilation = input.CreateCompilation();
        expectedResult = expectedResult.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new ControllerRegistrationGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("ControllerRegistrations.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }

    [Theory]
    [Trait("Area", "Partial")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }

                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddController<global::V1TestEntityController, global::V1TestEntity>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Partial controller class with base list on both parts")]
    [InlineData(
        """
                using k8s;
                using k8s.Models;
                using KubeOps.Abstractions.Entities;
                using KubeOps.Abstractions.Reconciliation.Controller;

                [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
                public sealed class V1TestEntity : IKubernetesObject<V1ObjectMeta>
                {
                }

                public sealed class V1TestEntityLabelSelector : IEntityLabelSelector<V1TestEntity>
                {
                    public ValueTask<string?> GetLabelSelectorAsync(CancellationToken cancellationToken) =>
                        ValueTask.FromResult<string?>("managed=true");
                }

                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }

                [LabelSelector(typeof(V1TestEntityLabelSelector))]
                public partial class V1TestEntityController : IEntityController<V1TestEntity>
                {
                }
                """,
        """
                     // <auto-generated>
                     // This code was generated by a tool.
                     // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                     // </auto-generated>
                     #pragma warning disable CS1591
                     using KubeOps.Abstractions.Builder;

                     public static class ControllerRegistrations
                     {
                         public static IOperatorBuilder RegisterControllers(this IOperatorBuilder builder)
                         {
                             builder.AddControllerWithLabelSelector<global::V1TestEntityController, global::V1TestEntity, global::V1TestEntityLabelSelector>();
                             return builder;
                         }
                     }
                     """,
        TestDisplayName = "Partial controller class with selector attribute on a separate part")]
    public void Should_Generate_Correct_Code_For_Partial_Controllers(string input, string expectedResult)
        => Should_Generate_Correct_Code(input, expectedResult);
}
