// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Reflection;

using FluentAssertions;

using KubeOps.Generator.Generators;
using KubeOps.Generator.Test.Entities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed partial class EntityDefinitionGeneratorTest
{
    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Not_Generate_Definitions_For_Entities_From_Referenced_Assemblies()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Generator.Test.Entities;
            using KubeOps.Abstractions.Reconciliation.Controller;
            using KubeOps.Abstractions.Reconciliation.Finalizer;

            public sealed class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyWithConstantValues>
            {
            }

            public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntityFromReferencedAssemblyInGlobalNamespace>
            {
            }
            """.CreateCompilation(
            additionalReferences: MetadataReference
                .CreateFromFile(typeof(V1TestEntityFromReferencedAssembly)
                    .GetTypeInfo().Assembly.Location));

        var driver = CSharpGeneratorDriver.Create(new EntityDefinitionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        output.SyntaxTrees.Any(s => s.FilePath.Contains("EntityDefinitions.g.cs")).Should().BeFalse();
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Only_Generate_Definitions_For_Locally_Declared_Entities()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Generator.Test.Entities;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "LocalEntity")]
            public sealed class V1LocalEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntityFromReferencedAssemblyWithConstantValues>
            {
            }
            """.CreateCompilation(
            additionalReferences: MetadataReference
                .CreateFromFile(typeof(V1TestEntityFromReferencedAssembly)
                    .GetTypeInfo().Assembly.Location));
        var expectedResult = """
            // <auto-generated>
            // This code was generated by a tool.
            // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            #pragma warning disable CS1591
            using KubeOps.Abstractions.Builder;
            using KubeOps.Abstractions.Entities;

            public static class EntityDefinitions
            {
                public static readonly EntityMetadata V1LocalEntity = new("LocalEntity", "v1", "testing.dev", null);
            }
            """.ReplaceLineEndings();

        var driver = CSharpGeneratorDriver.Create(new EntityDefinitionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        var result = output.SyntaxTrees
            .First(s => s.FilePath.Contains("EntityDefinitions.g.cs"))
            .ToString().ReplaceLineEndings();
        result.Should().Be(expectedResult);
    }
}
