// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

using FluentAssertions;

using KubeOps.Generator.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubeOps.Generator.Test;

public sealed class OperatorBuilderGeneratorTest
{
    private const string OperatorBuilderFileName = "OperatorBuilder.g.cs";

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Not_Generate_RegisterComponents_Without_Components_Or_Operator_Reference()
    {
        var inputCompilation = string.Empty.CreateCompilation();

        var driver = CSharpGeneratorDriver.Create(new OperatorBuilderGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        output.SyntaxTrees.Any(s => s.FilePath.Contains(OperatorBuilderFileName)).Should().BeFalse();
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Generate_Empty_RegisterComponents_When_Operator_Is_Referenced()
    {
        var operatorReference = string.Empty.CreateCompilation("KubeOps.Operator").EmitToImageReference();
        var inputCompilation = string.Empty.CreateCompilation(operatorReference);
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation).Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Generate_Own_Registrations_With_Assembly_Marker()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;
            using KubeOps.Abstractions.Reconciliation.Finalizer;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }

            public sealed class V1TestEntityFinalizer : IEntityFinalizer<V1TestEntity>
            {
            }
            """.CreateCompilation();
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                [assembly: global::KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("ControllerRegistrations", "FinalizerRegistrations")]
                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        builder.RegisterControllers();
                        builder.RegisterFinalizers();
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation).Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Only_Register_Existing_Component_Kinds()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation();
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                [assembly: global::KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("ControllerRegistrations", null)]
                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        builder.RegisterControllers();
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation).Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Register_Referenced_Assembly_Registrations()
    {
        var libCompilation = """
            [assembly: KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("LibA.ControllerRegistrations", "LibA.FinalizerRegistrations")]
            """.CreateCompilation("liba");
        var inputCompilation = string.Empty.CreateCompilation(libCompilation.EmitToImageReference());
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        global::LibA.ControllerRegistrations.RegisterControllers(builder);
                        global::LibA.FinalizerRegistrations.RegisterFinalizers(builder);
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation).Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Register_Own_And_Referenced_Assembly_Registrations()
    {
        var libCompilation = """
            [assembly: KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("LibA.ControllerRegistrations", null)]
            """.CreateCompilation("liba");
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation(libCompilation.EmitToImageReference());
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                [assembly: global::KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("ControllerRegistrations", null)]
                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        builder.RegisterControllers();
                        global::LibA.ControllerRegistrations.RegisterControllers(builder);
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation).Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Generate_Into_Configured_Namespace()
    {
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation();
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                [assembly: global::KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("MyOperator.ControllerRegistrations", null)]
                namespace MyOperator;
                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        builder.RegisterControllers();
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation, out _, "MyOperator").Should().Be(expectedResult);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Report_Diagnostic_And_Skip_Conflicting_Referenced_Registrations()
    {
        var libCompilation = """
            [assembly: KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("ControllerRegistrations", null)]
            """.CreateCompilation("liba");
        var inputCompilation = """
            using k8s;
            using k8s.Models;
            using KubeOps.Abstractions.Reconciliation.Controller;

            [KubernetesEntity(Group = "testing.dev", ApiVersion = "v1", Kind = "TestEntity")]
            public class V1TestEntity : IKubernetesObject<V1ObjectMeta>
            {
            }

            public sealed class V1TestEntityController : IEntityController<V1TestEntity>
            {
            }
            """.CreateCompilation(libCompilation.EmitToImageReference());
        var expectedResult =
            """
                // <auto-generated>
                // This code was generated by a tool.
                // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                #pragma warning disable CS1591
                using KubeOps.Abstractions.Builder;

                [assembly: global::KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("ControllerRegistrations", null)]
                internal static class OperatorBuilderExtensions
                {
                    public static IOperatorBuilder RegisterComponents(this IOperatorBuilder builder)
                    {
                        builder.RegisterControllers();
                        return builder;
                    }
                }
                """.ReplaceLineEndings();

        RunGenerator(inputCompilation, out var diagnostics).Should().Be(expectedResult);
        var diagnostic = diagnostics.Should().ContainSingle(d => d.Id == "KOG002").Subject;
        diagnostic.GetMessage().Should().Contain("liba");

        // The diagnostic is anchored at the declaration of the own component whose generated
        // registration class name is part of the conflict.
        diagnostic.Location.Should().NotBe(Location.None);
        diagnostic.Location.GetLineSpan().StartLinePosition.Line.Should().Be(9);
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Skip_Platform_Signed_Referenced_Assemblies()
    {
        // Discovery prunes assemblies carrying a .NET platform public key token without decoding
        // their attributes. A marked assembly that is public-signed with the runtime's key (token
        // of System.Private.CoreLib) must therefore be ignored, even though it carries the marker.
        var platformPublicKey = typeof(object).Assembly.GetName().GetPublicKey();
        var libCompilation = """
            [assembly: KubeOps.Abstractions.Builder.KubeOpsGeneratedRegistrations("LibA.ControllerRegistrations", null)]
            """.CreateCompilation("liba");
        libCompilation = libCompilation.WithOptions(
            ((CSharpCompilationOptions)libCompilation.Options)
                .WithCryptoPublicKey([.. platformPublicKey!])
                .WithPublicSign(true));
        var inputCompilation = string.Empty.CreateCompilation(libCompilation.EmitToImageReference());

        var driver = CSharpGeneratorDriver.Create(new OperatorBuilderGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        output.SyntaxTrees.Any(s => s.FilePath.Contains(OperatorBuilderFileName)).Should().BeFalse();
    }

    [Fact]
    [Trait("Area", "ReferencedRegistration")]
    public void Should_Ignore_Foreign_Attribute_Without_Abstractions_Reference()
    {
        // Discovery only decodes attributes of assemblies that reference KubeOps.Abstractions.
        // An assembly applying its own, same-named attribute from a different namespace (and thus
        // not referencing KubeOps.Abstractions at all) must not be picked up.
        var libCompilation = """
            [assembly: Fake.KubeOpsGeneratedRegistrations("Fake.ControllerRegistrations", null)]

            namespace Fake
            {
                [System.AttributeUsage(System.AttributeTargets.Assembly)]
                public sealed class KubeOpsGeneratedRegistrationsAttribute : System.Attribute
                {
                    public KubeOpsGeneratedRegistrationsAttribute(string? controllerRegistrations, string? finalizerRegistrations)
                    {
                    }
                }
            }
            """.CreateCompilation("libfake");
        var inputCompilation = string.Empty.CreateCompilation(libCompilation.EmitToImageReference());

        var driver = CSharpGeneratorDriver.Create(new OperatorBuilderGenerator());
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out ImmutableArray<Diagnostic> _,
            TestContext.Current.CancellationToken);

        output.SyntaxTrees.Any(s => s.FilePath.Contains(OperatorBuilderFileName)).Should().BeFalse();
    }

    private static string RunGenerator(Compilation inputCompilation)
        => RunGenerator(inputCompilation, out _);

    private static string RunGenerator(
        Compilation inputCompilation,
        out ImmutableArray<Diagnostic> diagnostics,
        string? generatorNamespace = null)
    {
        var driver = CSharpGeneratorDriver.Create(
            generators: [new OperatorBuilderGenerator().AsSourceGenerator()],
            optionsProvider: generatorNamespace is null
                ? null
                : TestHelperExtensions.CreateGeneratorNamespaceOptions(generatorNamespace));
        driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation,
            out var output,
            out diagnostics,
            TestContext.Current.CancellationToken);

        return output.SyntaxTrees
            .First(s => s.FilePath.Contains(OperatorBuilderFileName))
            .ToString().ReplaceLineEndings();
    }
}
