// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using k8s.Models;

namespace KubeOps.Abstractions.Crds;

/// <summary>
/// Factory interface for creating <see cref="V1CustomResourceDefinition"/> instances.
/// Implement this interface to customize the shape of CRDs generated by the operator.
/// </summary>
public interface ICrdResourceFactory
{
    /// <summary>
    /// Creates the <see cref="V1CustomResourceDefinition"/> resources for the given entity types.
    /// </summary>
    /// <param name="entityTypes">The entity types to transpile into CRDs.</param>
    /// <returns>The generated <see cref="V1CustomResourceDefinition"/> instances.</returns>
    IEnumerable<V1CustomResourceDefinition> CreateCustomResourceDefinitions(IReadOnlyCollection<Type> entityTypes);
}
