// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Text;

using KubeOps.Generator.Discovery;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace KubeOps.Generator.Generators;

[Generator]
internal sealed class ControllerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            EntityDiscovery.GetControllers(context).Combine(EntityDiscovery.GetEntities(context)),
            (spc, source) => Execute(spc, source.Left, source.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        EquatableArray<ControllerRegistration> controllers,
        EquatableArray<AttributedEntity> entities)
    {
        var declaration = CompilationUnit()
            .WithUsings(
                List(
                    new List<UsingDirectiveSyntax>
                    {
                        UsingDirective(IdentifierName("KubeOps.Abstractions.Builder")),
                    }))
            .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance)
            .WithMembers(SingletonList<MemberDeclarationSyntax>(ClassDeclaration("ControllerRegistrations")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .AddMembers(MethodDeclaration(IdentifierName("IOperatorBuilder"), "RegisterControllers")
                    .WithModifiers(
                        TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                    .WithParameterList(ParameterList(
                        SingletonSeparatedList(
                            Parameter(
                                    Identifier("builder"))
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.ThisKeyword)))
                                .WithType(
                                    IdentifierName("IOperatorBuilder")))))
                    .WithBody(Block(
                        controllers
                            .Where(c => entities.Any(e =>
                                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName))
                            .OrderBy(c => c.FullyQualifiedEntityName, StringComparer.Ordinal)
                            .Select(c => (c.FullyQualifiedController, Entity: entities.First(e =>
                                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName)))
                            .Select(e => ExpressionStatement(
                                InvocationExpression(
                                    MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("builder"),
                                        GenericName(Identifier("AddController"))
                                            .WithTypeArgumentList(
                                                TypeArgumentList(
                                                    SeparatedList<TypeSyntax>(new[]
                                                    {
                                                        IdentifierName(e.FullyQualifiedController),
                                                        IdentifierName(e.Entity.ClassDeclaration.FullyQualifiedName),
                                                    })))))))
                            .Append<StatementSyntax>(ReturnStatement(IdentifierName("builder"))))))))
            .NormalizeWhitespace();

        context.AddSource(
            "ControllerRegistrations.g.cs",
            SourceText.From(declaration.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }
}
