// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Text;

using KubeOps.Generator.Discovery;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace KubeOps.Generator.Generators;

[Generator]
internal sealed class ControllerRegistrationGenerator : IIncrementalGenerator
{
    // A controller supports a single selector kind. Combining [LabelSelector] and [FieldSelector] on one
    // controller used to silently register only the label selector; it is now a compile-time error.
    private static readonly DiagnosticDescriptor ConflictingSelectorAttributes = new(
        id: "KOG001",
        title: "Controller declares conflicting selector attributes",
        messageFormat: "Controller '{0}' declares both [LabelSelector] and [FieldSelector]. A controller " +
            "supports only one selector kind; split it into separate controllers.",
        category: "KubeOps.Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            EntityDiscovery.GetControllers(context).Combine(EntityDiscovery.GetEntities(context)),
            (spc, source) => Execute(spc, source.Left, source.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        EquatableArray<ControllerRegistration> controllers,
        EquatableArray<AttributedEntity> entities)
    {
        // Controllers that declare both a label and a field selector are reported as an error and excluded
        // from registration, so no misleading label-only registration is emitted for them.
        var validControllers = new List<ControllerRegistration>();
        foreach (var controller in controllers)
        {
            if (controller.FullyQualifiedLabelSelector is not null &&
                controller.FullyQualifiedFieldSelector is not null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ConflictingSelectorAttributes,
                    controller.Location?.ToLocation() ?? Location.None,
                    controller.FullyQualifiedController));
                continue;
            }

            validControllers.Add(controller);
        }

        var declaration = CompilationUnit()
            .WithUsings(
                List(
                    new List<UsingDirectiveSyntax>
                    {
                        UsingDirective(IdentifierName("KubeOps.Abstractions.Builder")),
                    }))
            .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance)
            .WithMembers(SingletonList<MemberDeclarationSyntax>(ClassDeclaration("ControllerRegistrations")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .AddMembers(MethodDeclaration(IdentifierName("IOperatorBuilder"), "RegisterControllers")
                    .WithModifiers(
                        TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                    .WithParameterList(ParameterList(
                        SingletonSeparatedList(
                            Parameter(
                                    Identifier("builder"))
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.ThisKeyword)))
                                .WithType(
                                    IdentifierName("IOperatorBuilder")))))
                    .WithBody(Block(
                        validControllers
                            .Where(c => entities.Any(e =>
                                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName))
                            .OrderBy(c => c.FullyQualifiedEntityName, StringComparer.Ordinal)
                            .Select(c => (Controller: c, Entity: entities.First(e =>
                                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName)))
                            .Select(e => ExpressionStatement(
                                InvocationExpression(
                                    MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("builder"),
                                        RegistrationMethodFor(e.Controller, e.Entity)))))
                            .Append<StatementSyntax>(ReturnStatement(IdentifierName("builder"))))))))
            .NormalizeWhitespace();

        context.AddSource(
            "ControllerRegistrations.g.cs",
            SourceText.From(declaration.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }

    // Chooses the builder method matching the controller's selector attributes: a [LabelSelector] or
    // [FieldSelector] attribute switches to the corresponding AddControllerWith…Selector registration.
    private static GenericNameSyntax RegistrationMethodFor(ControllerRegistration controller, AttributedEntity entity)
    {
        var typeArguments = new List<TypeSyntax>
        {
            IdentifierName(controller.FullyQualifiedController),
            IdentifierName(entity.ClassDeclaration.FullyQualifiedName),
        };

        string methodName;
        switch (controller)
        {
            case { FullyQualifiedLabelSelector: { } labelSelector }:
                methodName = "AddControllerWithLabelSelector";
                typeArguments.Add(IdentifierName(labelSelector));
                break;
            case { FullyQualifiedFieldSelector: { } fieldSelector }:
                methodName = "AddControllerWithFieldSelector";
                typeArguments.Add(IdentifierName(fieldSelector));
                break;
            default:
                methodName = "AddController";
                break;
        }

        return GenericName(Identifier(methodName))
            .WithTypeArgumentList(TypeArgumentList(SeparatedList(typeArguments)));
    }
}
