// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Text;

using KubeOps.Generator.Discovery;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace KubeOps.Generator.Generators;

[Generator]
internal sealed class FinalizerRegistrationGenerator : IIncrementalGenerator
{
    private const byte MaxNameLength = 63;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            EntityDiscovery.GetFinalizers(context)
                .Combine(EntityDiscovery.GetEntities(context))
                .Combine(GeneratorOptions.GetGeneratorNamespace(context)),
            (spc, source) => Execute(spc, source.Left.Left, source.Left.Right, source.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        EquatableArray<FinalizerRegistration> finalizerRegistrations,
        EquatableArray<AttributedEntity> entities,
        string? generatorNamespace)
    {
        var finalizers = finalizerRegistrations
            .Where(c => entities.Any(e =>
                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName))
            .OrderBy(c => c.FullyQualifiedEntityName, StringComparer.Ordinal)
            .Select(c => (c.FullyQualifiedFinalizer, c.IdentifierName, Entity: entities.First(e =>
                e.ClassDeclaration.FullyQualifiedName == c.FullyQualifiedEntityName))).ToList();

        if (finalizers.Count == 0)
        {
            return;
        }

        var declaration = CompilationUnit()
            .WithUsings(
                List(
                    new List<UsingDirectiveSyntax> { UsingDirective(IdentifierName("KubeOps.Abstractions.Builder")), }))
            .WithLeadingTrivia(AutoGeneratedSyntaxTrivia.Instance)
            .AddNamespaceScope(generatorNamespace)
            .AddMembers(ClassDeclaration("FinalizerRegistrations")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .WithMembers(List<MemberDeclarationSyntax>(finalizers.Select(f =>
                    FieldDeclaration(
                            VariableDeclaration(
                                    PredefinedType(
                                        Token(SyntaxKind.StringKeyword)))
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator(Identifier($"{f.IdentifierName}Identifier"))
                                            .WithInitializer(
                                                EqualsValueClause(
                                                    LiteralExpression(
                                                        SyntaxKind.StringLiteralExpression,
                                                        Literal(FinalizerName(f))))))))
                        .WithModifiers(
                            TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.ConstKeyword))))))
                .AddMembers(MethodDeclaration(IdentifierName("IOperatorBuilder"), "RegisterFinalizers")
                    .WithModifiers(
                        TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                    .WithParameterList(ParameterList(
                        SingletonSeparatedList(
                            Parameter(
                                    Identifier("builder"))
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.ThisKeyword)))
                                .WithType(
                                    IdentifierName("IOperatorBuilder")))))
                    .WithBody(Block(
                        finalizers.Select(f => ExpressionStatement(
                                InvocationExpression(
                                        MemberAccessExpression(
                                            SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("builder"),
                                            GenericName(Identifier("AddFinalizer"))
                                                .WithTypeArgumentList(
                                                    TypeArgumentList(
                                                        SeparatedList<TypeSyntax>(new[]
                                                        {
                                                            IdentifierName(f.FullyQualifiedFinalizer),
                                                            IdentifierName(f.Entity.ClassDeclaration.FullyQualifiedName),
                                                        })))))
                                    .WithArgumentList(
                                        ArgumentList(
                                            SingletonSeparatedList(
                                                Argument(
                                                    IdentifierName($"{f.IdentifierName}Identifier")))))))
                            .Append<StatementSyntax>(ReturnStatement(IdentifierName("builder")))))))
            .NormalizeWhitespace();

        context.AddSource(
            "FinalizerRegistrations.g.cs",
            SourceText.From(declaration.ToFullString(), Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }

    private static string FinalizerName((string FullyQualifiedFinalizer, string IdentifierName, AttributedEntity Entity) finalizer)
    {
        var finalizerName = finalizer.IdentifierName.ToLowerInvariant();
        var name =
            $"{finalizer.Entity.Group}/{finalizerName}{(finalizerName.EndsWith("finalizer") ? string.Empty : "finalizer")}"
                .TrimStart('/');
        return name.Length > MaxNameLength ? name.Substring(0, MaxNameLength) : name;
    }
}
